### ISSUE TITLE
ToDo：关于下个版本`1.9.3`的一些情况

### ISSUE THREAD

**Issue by maboloshi** [maboloshi/github-chinese#159]
- [x] 进一步优化中文环境设置
   - [x] 当前使用`document-start`脚本载入机制, 导致存在一些 [bug](146#discussioncomment-9696969), 打算使用`window.addEventListener('DOMContentLoaded', init);`延迟`init`的载入 (灵感来自 buiawpkgew1/github-chinese#98)
- [x] 使用 ~~`window.addEventListener('DOMContentLoaded', ...)`~~ `document.addEventListener('turbo:load', ...)`代替`setTimeout`
- [ ] ~~更新`page`更新逻辑~~
   - [ ] ~~使用`Turbo`原生的`before-fetch-request`事件及`detail.url`对象 最快获取新页面的`url`. 目前,发现对于需要`class`筛选的效果不好~~
   - [ ] ~~监视`document.body`的`class`属性变化即可~~
- [ ] 词库清理计划（#115）
- [x] 翻译 GitHub 一些附属网站，如 `githubstatus.com` 与 `skills.github.com` 8cfcfb69
- [x] 修复 https://github.com/maboloshi/github-chinese/discussions/146#discussioncomment-9855443 ，并优化`getPage`函数 c2dd05d
- [x] 优化`traverseNode`和`transElement`函数 a9979fb8
- [ ] 监听`body`变化，优化`突变翻译处理`
   - [x] 在`mutations.filter`过程中，提前过滤：
      - [x] 特定页面的特定元素，包括不限于修复代码新建和编辑页面触发逗号 bug 的问题；（ 95b0d8fc , 0ed0cf94 ）
      - [x] 仅对特定页面启用筛选`字符数据`的变更 95b0d8fc
   - [ ] ~~进一步探讨`MutationObserver.takeRecords()` (灵感来自 buiawpkgew1/github-chinese#98)~~
   - [x] 引入`ignoreMutationSelectorPage`规则，仅对`突变`翻译有效
   - [ ] ~~使用`lastFilteredMutations`记录上一次处理的突变记录。上一次`traverseNode`引发的突变一定在这个`lastFilteredMutations`里且小于它。在下轮过滤突变时，将`lastFilteredMutations`作为被过滤的条件之一~~
- [ ] 考虑`reIgnoreClass`，`reIgnoreItemprop`，`ignoreId`，`ignoreTag`是否区分全局和特定页面
- [x] 考虑引入全局缓存模式，减少重复构建包括不限于基于`page`变化的忽略规则、正则规则数组等 e0e5fc547249cc8a0e703bb87fa09b3454a1018d

**Comment by maboloshi** [comment]
# 参考资料

## `Turbo`动态内容加载技术
项目: https://github.com/hotwired/turbo

Turbo 是由 Basecamp 开发的，用于加速网页导航，使页面在用户导航时不进行完整的页面刷新，而是仅更新页面的部分内容。

> GitHub 使用了此技术

### 常用的 Turbo 事件
Turbo（前身为 Turbolinks）提供了一些事件供开发者监听，以便在页面导航或内容更新时执行特定操作。以下是一些常用的 Turbo 事件：

### Turbo Events

1. **`turbo:click`**:
   - 在用户点击链接时触发。
   - 可以用于在链接点击时执行一些操作，例如记录点击事件。

2. **`turbo:before-visit`**:
   - 在 Turbo 开始导航到新页面之前触发。
   - 可以用于取消或重定向导航。

3. **`turbo:visit`**:
   - 在 Turbo 开始导航到新页面时触发。

4. **`turbo:before-fetch-request`**:
   - 在 Turbo 发起网络请求之前触发。
   - 可以用于修改请求或添加自定义头。

5. **`turbo:before-fetch-response`**:
   - 在 Turbo 收到网络响应之前触发。
   - 可以用于检查响应或处理错误。

6. **`turbo:before-render`**:
   - 在 Turbo 准备将新内容渲染到页面之前触发。
   - 可以用于修改即将渲染的内容。

7. **`turbo:render`**:
   - 在 Turbo 将新内容渲染到页面时触发。

8. **`turbo:load`**:
   - 在 Turbo 完成导航并且新内容已经完全渲染到页面时触发。
   - 类似于传统的 `DOMContentLoaded` 事件，但在每次 Turbo 导航后都会触发。

9. **`turbo:frame-load`**:
   - 在一个 Turbo Frame 加载完成时触发。

10. **`turbo:frame-render`**:
    - 在一个 Turbo Frame 准备将新内容渲染到页面时触发。

11. **`turbo:submit-start`**:
    - 在表单提交开始时触发。

12. **`turbo:before-cache`**:
    - 在页面被缓存之前触发。
    - 可以用于在页面缓存之前执行一些清理操作。

### 示例代码

以下是如何使用这些事件的示例代码：

```javascript
// 在页面初始加载完成时执行
window.addEventListener('DOMContentLoaded', (event) => {
    console.log('DOMContentLoaded');
    executeTranslation();
});

// 在每次 Turbo 导航完成并渲染新内容后执行
document.addEventListener('turbo:load', (event) => {
    console.log('Turbo load');
    executeTranslation();
});

// 监听其他 Turbo 事件
document.addEventListener('turbo:click', (event) => {
    console.log('Turbo click', event);
});

document.addEventListener('turbo:before-visit', (event) => {
    console.log('Turbo before visit', event);
});

document.addEventListener('turbo:visit', (event) => {
    console.log('Turbo visit', event);
});

document.addEventListener('turbo:before-fetch-request', (event) => {
    console.log('Turbo before fetch request', event);
});

document.addEventListener('turbo:before-fetch-response', (event) => {
    console.log('Turbo before fetch response', event);
});

document.addEventListener('turbo:before-render', (event) => {
    console.log('Turbo before render', event);
});

document.addEventListener('turbo:render', (event) => {
    console.log('Turbo render', event);
});

document.addEventListener('turbo:frame-load', (event) => {
    console.log('Turbo frame load', event);
});

document.addEventListener('turbo:frame-render', (event) => {
    console.log('Turbo frame render', event);
});

document.addEventListener('turbo:submit-start', (event) => {
    console.log('Turbo submit start', event);
});

document.addEventListener('turbo:before-cache', (event) => {
    console.log('Turbo before cache', event);
});

function executeTranslation() {
    // 使用 CSS 选择器找到页面上的元素，并将其文本内容替换为预定义的翻译
    transBySelector();
    if (page === "repository") { // 仓库简介翻译
        transDesc(".f4.my-3");
    } else if (page === "gist") { // Gist 简介翻译
        transDesc(".gist-content [itemprop='about']");
    }
}
```

### 解释

1. **初始加载**: `DOMContentLoaded` 事件确保代码在初始加载时执行。
2. **Turbo 导航完成**: `turbo:load` 事件确保代码在每次 Turbo 导航完成后执行。
3. **其他事件**: 其他 Turbo 事件监听器用于在特定导航或请求过程中执行自定义操作。

通过监听这些事件，你可以在 GitHub 页面导航和内容动态加载时执行特定的功能，确保你的代码在合适的时机运行。

**Comment by wuyuncheng-26** [comment]
翻译中文日期目前尚未合并到主分支
需要体验的可以去看一下 [`Test_zh-CN_LangEnvSet`](https://github.com/maboloshi/github-chinese/tree/Test_zh-CN_LangEnvSet) 分支下的 [`main.user.js`](https://github.com/maboloshi/github-chinese/raw/Test_zh-CN_LangEnvSet/main.user.js)

**Comment by buiawpkgew1** [comment]
> * 监听`body`变化，优化`突变翻译处理`

<details><summary>处理的一些建议？</summary>
<p>
    <h3>1. 优化MutationObserver配置</h3>
    <p>确保只监控必要的属性和类型的变更，这可以减少MutationObserver的开销。</p>
    <h3>2. 单一MutationObserver实例</h3>
    <p>尽可能使用单一的MutationObserver实例来监控所有需求，避免创建多个观察者，因为这可能会消耗更多资源。</p>
    <h3>3. 缓存翻译结果</h3>
    <p>代码中已经包含了translationCache的缓存机制。确保在翻译规则发生变化时更新或清除缓存。</p>
    <h3>4. 精炼翻译逻辑</h3>
    <p>优化翻译逻辑，采用更高效的字符串操作技巧，并尽量减少DOM查找次数。</p>
    <h3>5. 减少不必要的DOM变动</h3>
    翻译元素时，尽量减少DOM的修改次数。批量更新可以提高效率。
    <h3>6. 异步调用使用Async/Await</h3>
    对于如translateDescText中的异步网络请求，考虑使用async/await来增强可读性和错误处理。
    <h3>7. 错误处理</h3>
    加强错误处理，确保代码的健壮性。
    <h3>8. 性能考量</h3>
    <p>注意性能影响，特别是在处理大型文档或频繁的DOM变更时。</p>
</p>
</details>

**Comment by maboloshi** [comment]
> > * 监听`body`变化，优化`突变翻译处理`
> 处理的一些建议？（来自通义灵码）

哈哈果然是AI, 不过可能还是`chatGPT`跟智能一点

**Comment by maboloshi** [comment]
> > * 监听`body`变化，优化`突变翻译处理`
> 
> 处理的一些建议？（来自通义灵码）

目前，考虑
1. 使用`lastFilteredMutations`记录上一次处理的突变记录。上一次`traverseNode`引发的突变一定在这个`lastFilteredMutations`里且小于它
2. 在下轮过滤突变时，将`lastFilteredMutations`作为被过滤的条件之一
3. 优化过滤规则，尽量减少不必要的 DOM 操作和数组检查，提升整体性能。
